### PR TITLE
Improving ReadMe Explanation

### PR DESCRIPTION
**Pull request by devajmeireles**
This PR increases the explanations in README.md to resolve the doubt associated with cases like this: https://github.com/JoshuaBedford/lando-zsh/issues/3

### CODE REVIEW

**Comment by JoshuaBedford** [comment]
@ajmeireles I'm considering this PR and other improvements to the documentation. Thank you for the time spent!

Did you utilize this plugin standalone (as a git pull into custom plugins) or did you utilize the version that comes with oh-my-zsh?

**Comment by devajmeireles** [comment]
> @ajmeireles I'm considering this PR and other improvements to the documentation. Thank you for the time spent!
> 
> Did you utilize this plugin standalone (as a git pull into custom plugins) or did you utilize the version that comes with oh-my-zsh?

I use the plugin by the OhMyZsh. Should the adjustment be done there, or do you suggest that I stop using the other to use yours from this repository?

**Comment by JoshuaBedford** [comment]
> > @ajmeireles I'm considering this PR and other improvements to the documentation. Thank you for the time spent!
> > Did you utilize this plugin standalone (as a git pull into custom plugins) or did you utilize the version that comes with oh-my-zsh?
> 
> I use the plugin by the OhMyZsh. Should the adjustment be done there, or do you suggest that I stop using the other to use yours from this repository?

Keep it the same for now. I need to look into how to recommend variable changes for the plugin controlled by the master oh-my-zsh repository. The issue i foresee would be future updates would overwrite (and break) the plugin if you only change it there.

The short term solution would be to clone this repository into the custom plugins folder and make changes there. I'm looking into a longer-term solution that will allow customizations and configurations through oh-my-zsh that wouldn't be overwritten by updates.

**Comment by JoshuaBedford** [comment]
Closing this pull request. I've updated the README on how to properly update the plugin settings without editing the plugin.

**Pull request closed without merging**
